# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ProtMamba-ssm',
                'doc_host': 'https://Bitbol-Lab.github.io',
                'git_url': 'https://github.com/Bitbol-Lab/ProtMamba-ssm',
                'lib_path': 'ProtMamba_ssm'},
  'syms': {'ProtMamba_ssm.core': {'ProtMamba_ssm.core.foo': ('core.html#foo', 'ProtMamba_ssm/core.py')}}}
